config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :job_postings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :description, presence: true, length: { minimum: 3 }
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  validates :title, :description, presence: true, length: { minimum: 3 }
end

app/controllers/_forms_controller.rb
class FormsController < ApplicationController
  before_action :set__form, only: [:show, :edit, :update, :destroy]

  # GET /_forms
  # GET /_forms.json
  def index
    @_forms = Form.all
  end

  # GET /_forms/1
  # GET /_forms/1.json
  def show
  end

  # GET /_forms/new
  def new
    @_form = Form.new
  end

  # GET /_forms/1/edit
  def edit
  end

  # POST /_forms
  # POST /_forms.json
  def create
    @_form = Form.new(_form_params)

    respond_to do |format|
      if @_form.save
        format.html { redirect_to @_form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @_form }
      else
        format.html { render :new }
        format.json { render json: @_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /_forms/1
  # PATCH/PUT /_forms/1.json
  def update
    respond_to do |format|
      if @_form.update(_form_params)
        format.html { redirect_to @_form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @_form }
      else
        format.html { render :edit }
        format.json { render json: @_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /_forms/1
  # DELETE /_forms/1.json
  def destroy
    @_form.destroy
    respond_to do |format|
      format.html { redirect_to _forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set__form
      @_form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def _form_params
      params.require(:_form).permit(:index, :edit, :show, :new)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /job_postings
  # GET /job_postings.json
  def index
    @job_postings = JobPosting.order(sort_column + " " + sort_direction)
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
    @job_posting = JobPosting.find(params[:id])
  end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new
  end

  # GET /job_postings/1/edit
  def edit
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to job_postings_url, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
        format.html { redirect_to job_postings_url, notice: 'Job posting was not created.' }
      end
    end
  end

  # PATCH/PUT /job_postings/1
  # PATCH/PUT /job_postings/1.json
  def update
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to job_postings_url, notice: 'Job posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { redirect_to job_postings_url, notice: 'Job posting could not be updated.' }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting.destroy
    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_posting_params
      params.require(:job_posting).permit(:title, :description, :hiring_manager, :email)
    end

    def sort_column ## this sets the default for index page
      JobPosting.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
    end

    def sort_direction ## this tells page to display in descending order by default
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    job = Job.create(job_params)
    flash[:notice] = "Job posted!"
    redirect_to jobs_path
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update_attributes(job_params)
    flash[:notice] = "Job listing successfully updated!"
    redirect_to jobs_path
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "Job '#{@job.title}' deleted!"
    redirect_to jobs_path
  end

  def show
    @job = Job.find(params[:id])
  end

    private

    def job_params
      params.require(:job).permit(:title, :description)
    end

end

app/helpers/_forms_helper.rb
module FormsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/job_postings/_form.html.erb
<%= form_for(job_posting) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :hiring_manager %>
    <%= f.text_field :hiring_manager %>
  </div>
  <div>
    <%= f.submit "Post Job" %>
  </div>
<% end %>

app/views/job_postings/edit.html.erb
<h1>Editing Job Posting</h1>

<%= render 'form', job_posting: @job_posting %>

<%= link_to 'Show', @job_posting %> |
<%= link_to 'Back', job_postings_path %>

app/views/job_postings/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>


<h1>Open Jobs</h1>

<table class="tableous">
  <tr>
    <th><%= sortable "title", "Job Name" %></th>
    <th><%= sortable "description", "Job Description" %></th>
    <th><%= sortable "updated_at", "Date Posted" %></th>
    <th>Full Job Posting</th>
  </tr>
  <% @job_postings.each do |job| %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.description %></td>
      <td><%= job.updated_at %></td>
      <td><%= link_to("Show full job posting", job_posting_path(job)) %></td>
    </tr>
  <% end %>
</table>

app/views/job_postings/new.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<h1>New Job Posting</h1>

<%= render 'form', job_posting: @job_posting %>

<%= link_to 'Back', job_postings_path %>

app/views/job_postings/show.html.erb
<h1><%= @job_posting.title %></h1>

<p><%= @job_posting.description %></p>
<p><%= @job_posting.email %></p>
<p><%= @job_posting.hiring_manager %></p>

<p>Created at: <%= @job_posting.created_at %></p>
<p>Updated at: <%= @job_posting.updated_at %></p>
<h5><%= link_to "Edit Posting", edit_job_posting_path(@job_posting)%></h5>
<h5><%= link_to 'Delete Posting', @job_posting, method: :delete %></h5>

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <%= f.label(:title) %>
    <%= f.text_field(:title) %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit ("Post Job") %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>

<%= render "form" %>

app/views/jobs/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>


<h1>RailsBridgeCorp Open Jobs</h1>

<% @jobs.each do |job| %>
  <h3><%= job.title %></h3>
  <p><%= job.description %></p>
  <%= link_to("Show full job posting", job_path(job)) %>
<% end %>

app/views/jobs/new.html.erb
<h1>Add a job</h1>

<%= render "form" %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>

<p><%= @job.description %></p>
<p>Created at: <%= @job.created_at %></p>
<p>Updated at: <%= @job.updated_at %></p>
<h5><%= link_to "Edit Posting", edit_job_path(@job)%></h5>
<h5><%= link_to 'Delete Posting', @job, method: :delete %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="clearfix">
      <div class="left-nav">
        <ul>
          <li><%= link_to "Home", '/job_postings' %></li>
        </ul>
      </div>
      <div class="right-nav">
        <ul>
          <li><%= link_to "Add Job", '/job_postings/new' %></li>
        </ul>
      </div>
    </header>

    <div class="content">
      <%= yield %>
    </div>

  </body>
</html>